### PR TITLE
Properly deserialize uri values

### PR DESCRIPTION
**Pull request by JeroenBrinkman**
Tests are overrated

### CODE REVIEW

**Comment by pieterbos** [comment]
This actually changes the data type of value to URI, not just the deserialization. Considering the specs that’s probably a good thing, but it’s a bit more major change :)

**Comment by pieterbos** [comment]
Added a test, and the previous implementation works fine with json serialization and deseralization, and the resulting JSON is good as well. I'm merging the test because it was missing anyway. @JeroenBrinkman could you explain why you want to change the URI to String in DvURI?

**Comment by bobvanderlinden** [comment]
When deserializing the set method is called with a string argument. Since [openehr](http://www.openehr.org/releases/1.0.1/reference-models/openEHR/UML/HTML/Browsable/_9_0_76d0249_1109068346736_56077_4493Report.html) also describes an DV_URI as a type with a string value, it seemed correct to have the same in Archie. Because the underlying type will still be Uri, the String value is still parsed and validated as an Uri.

**Comment by bobvanderlinden** [comment]
Special serialization tricks are used to deserialize DvTime: https://github.com/nedap/archie/blob/master/src/main/java/com/nedap/archie/rm/datavalues/quantity/datetime/DvTime.java
The same would be needed for DvURI. We couldn't directly get (de)serialization to work properly and it seemed more complex and less following the openehr specs. That's mainly why we switched to using String and letting URI validation/parsing happen inside the setter.

**Comment by pieterbos** [comment]
For json serialization and deserialization, this should be covered by the test I added. It serializes the dv uri - which outputs a simple string - and deserializes it again, with an assertion to check that it’s correct. 

However, if you mean creating objects in our EHR-db, that’s a different scope and should not be fixed here. I can show you where that happens in January, it’s not in this repo :)

As in the string or Uri argument, openEHR allows for implementations to substitute some types, such as url. That’s what we use here, and also for the dates and times. There’s some additional logic that does conversion of these kinds of substitutions. One could argue that it’s better to use a string, but in that case we need to implement some additional methods to allow some defined operations.

**Comment by bobvanderlinden** [comment]
Ah that's good to know. I'm working from home today 🤧, but I'll drop by later this week for more info. Thanks for the explanation.

**Pull request merged**
